name: Hello World

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Say Hello
        run: echo "Hola mundo desde GitHub Actions!"
      - name: set up python
        run: python --version
      - name: Install Dependencies
        run: python -m pip install --upgrade pip
             pip install -r requirements.txt
